apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-jegan  # Replace 'jegan' with your name
spec:
  selector:
    matchLabels:
      app: wordpress
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
