apiVersion: v1
kind: Secret
metadata:
  name: wordpress-login-credentials
stringData:
  username: root
  password: root@123
  replication-password: repl@123
  # ProxySQL has its own admin interface on port 6032.
  # These credentials protect that admin interface.
  proxysql-admin-user: proxyadmin
  proxysql-admin-password: proxyadmin@123
